version: '2'
services:
  zookeeper:
    image: eventuateio/eventuate-zookeeper:0.4.0.RELEASE
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
      - 1883:1883
      - 61614:61614

  rabbitmq:
    build: ./rabbitmq
    ports:
      - 5672:5672

  postgres:
    image: eventuateio/eventuate-postgres:0.6.0.RELEASE
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate

  cdcservice:
    image: eventuateio/eventuate-cdc-service:0.4.0.RELEASE
    links:
      - postgres
      - activemq
      - rabbitmq
      - zookeeper
    ports:
      - "8099:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_TEST_ON_BORROW: "true"
      SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_READER_NAME: PostgresWalReader
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      ACTIVEMQ_URL: tcp://activemq:61616
      RABBITMQ_URL: rabbitmq