version: '2'
services:
  zookeeper:
    image: eventuateio/eventuate-zookeeper:0.4.0.RELEASE
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: eventuateio/eventuate-kafka:0.3.0.RELEASE
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  mssql:
    image: eventuateio/eventuate-mssql:0.4.0.RELEASE
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Eventuate123!
      ACCEPT_EULA: Y

  cdcservice:
    image: eventuateio/eventuate-cdc-service:0.4.0.RELEASE
    links:
      - mssql
      - kafka
      - zookeeper
    ports:
      - "8099:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=eventuate
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Eventuate123!
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_READER_NAME: MsSqlReader
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}