version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-tram-core-examples-basic
    steps:
      - checkout
      - restore_cache:
          key: eventuate-tram-core-examples-basic-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./gradlew testClasses
      - run: TERM=dumb ./mvnw test-compile
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: eventuate-tram-core-examples-basic-{{ checksum "gradle.properties" }}
      - run: TERM=dumb ./build-and-test-all-maven.sh
      - run: TERM=dumb ./build-and-test-all-mysql-binlog-kafka.sh
      - run: TERM=dumb ./build-and-test-all-mssql-polling-kafka.sh
      - run: TERM=dumb ./build-and-test-all-postgres-wal-activemq.sh
      - run: TERM=dumb ./build-and-test-all-postgres-wal-rabbitmq.sh
      - store_test_results:
          path: "*/build/test-results"
